name             'crystal'
maintainer       'Vijay Dhama'
maintainer_email 'vjdhama26@gmail.com'
license          'MIT'
description      'Installs/Configures crystal'
long_description 'Cookbook for installing crystal'
version          '0.2.2'
